// ============================================================
//  PHASE 4 — CODE GENERATOR
//  AST → JavaScript source code string
// ============================================================

class CodeGenerator {
  constructor() {
    this.indent = 0;
    this.lines  = [];
  }

  pad() { return '  '.repeat(this.indent); }

  emit(line) { this.lines.push(this.pad() + line); }

  generate(node) {
    switch (node.type) {
      case 'Program': {
        this.emit('// ── Generated by HinglishScript Compiler ──');
        node.body.forEach(s => this.genStmt(s));
        return this.lines.join('\n');
      }
      default: throw new Error(`CodeGen: unexpected root node ${node.type}`);
    }
  }

  genStmt(node) {
    switch (node.type) {
      case 'VarDecl': this.emit(`let ${node.name} = ${this.genExpr(node.value)};`); break;
      case 'Assign':  this.emit(`${node.name} = ${this.genExpr(node.value)};`);     break;
      case 'Print':   this.emit(`__print(${this.genExpr(node.value)});`);            break;
      case 'If': {
        this.emit(`if (${this.genExpr(node.cond)}) {`);
        this.indent++;
        node.then.forEach(s => this.genStmt(s));
        this.indent--;
        if (node.else && node.else.length > 0) {
          this.emit('} else {');
          this.indent++;
          node.else.forEach(s => this.genStmt(s));
          this.indent--;
        }
        this.emit('}');
        break;
      }
      case 'While': {
        this.emit(`while (${this.genExpr(node.cond)}) {`);
        this.indent++;
        node.body.forEach(s => this.genStmt(s));
        this.indent--;
        this.emit('}');
        break;
      }
      default: throw new Error(`CodeGen: unknown statement ${node.type}`);
    }
  }

  genExpr(node) {
    switch (node.type) {
      case 'Num':   return String(node.value);
      case 'Str':   return `"${node.value}"`;
      case 'Bool':  return node.value ? 'true' : 'false';
      case 'Ident': return node.name;
      case 'Unary': return `-(${this.genExpr(node.expr)})`;
      case 'BinOp': return `(${this.genExpr(node.left)} ${node.op} ${this.genExpr(node.right)})`;
      default: throw new Error(`CodeGen: unknown expression ${node.type}`);
    }
  }
}
